import Head from 'next/head';
import { Layout } from '@/components/Layout/Layout';
import { Guide } from '@/components/Guide/Guide';

export default function Home() {
  return (
    <>
      <Head>
        <title>Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout headTitle="Users" breadcrumbs={[{ title: 'Dashboard', link: '/' }]}>
        <Guide />
      </Layout>
    </>
  );
}
